name: Post Benchmark Data

on:
  workflow_run:
    workflows: ["Benchmark"]
    types:
      - completed

jobs:
  fetch-timings:
    name: Fetch Benchmark Timings & Upload to R2
    runs-on: warp-ubuntu-latest-x64-8x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Benchmark Workflow Run Details
        id: get_run
        uses: actions/github-script@v7
        with:
          script: |
            // This script uses the context of the triggering workflow run
            const run_id = context.payload.workflow_run.id;
            console.log(github);
            const { data: jobs } = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              run_id: run_id
            });
            console.log(jobs);
            // Extract job details including start and completion times.
            const timings = jobs.jobs.map(job => {
              const start = new Date(job.started_at);
              const end = new Date(job.completed_at);
              const duration = Math.round((end - start) / 1000); // duration in seconds
              return {
                job: job.name,
                duration: duration,
                started_at: job.started_at,
                completed_at: job.completed_at
              };
            });
            core.setOutput("timings", JSON.stringify(timings, null, 2));
            console.log(timings);
            return timings;
      - name: Write Timings to File
        run: |
          echo "${{ steps.get_run.outputs.timings }}" > timings.json
          cat timings.json

      - name: Set AWS Credentials for R2
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

      - name: Upload merged timings to R2
        run: |
          # Capture the current run ID and upload time in ISO8601 format
          RUN_ID=${{ github.run_id }}
          UPLOAD_TIME=$(date --utc +'%Y-%m-%dT%H:%M:%SZ')

          # Upload the updated JSON file to R2 using the specified path
          aws s3 cp timings.json s3://warpbuild-benchmarks/docker/posthog/timings/${UPLOAD_TIME}-${RUN_ID}.json --acl public-read --endpoint-url ${{ secrets.R2_ENDPOINT }}
