name: Sync
on:
  workflow_dispatch: {}
  # schedule:
  # - cron: "*/10 * * * *" # Runs every 10 minutes

jobs:
  sync:
    name: Sync With Upstream
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout with GitHub App Token
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Update Upstream Submodule
        run: |
          git submodule init
          git submodule update --remote --merge

          # Get the upstream commit message
          UPSTREAM_COMMIT_MSG=$(cd upstream && git log -1 --pretty=%B)

          # Use the upstream commit message
          git commit -am "${UPSTREAM_COMMIT_MSG}" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
